name: gradle
version: 'latest'
version-script: cat $SNAPCRAFT_STAGE/version
summary: Accelerate developer productivity
description: |
  From mobile apps to microservices, from small startups to big enterprises,
  Gradle helps teams build, automate and deliver better software, faster.
grade: stable
confinement: classic

parts:
  gradle:
    plugin: nil
    override-build: |
      snapcraftctl build
      RELEASE_INFO=$(curl https://services.gradle.org/versions/current -s)
      URL=$(echo $RELEASE_INFO | jq .downloadUrl -r)
      VERSION=$(echo $RELEASE_INFO | jq .version -r)
      echo $VERSION > $SNAPCRAFT_STAGE/version
      wget $URL -O gradle.zip
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/opt"
      unzip -q -d "${SNAPCRAFT_PART_INSTALL}/opt" gradle.zip
      mv "${SNAPCRAFT_PART_INSTALL}/opt/gradle-${VERSION}" "${SNAPCRAFT_PART_INSTALL}/opt/gradle"
      rm gradle.zip
    build-packages:
      - curl
      - jq
      - wget
      - unzip
      # https://forum.snapcraft.io/t/resolve-package-contains-external-symlinks-error-when-trying-to-snap/2963/2
      - ca-certificates
      - ca-certificates-java
      - openjdk-8-jre-headless
    stage-packages:
      - openjdk-8-jdk-headless

apps:
  gradle:
    command: opt/gradle/bin/gradle
    environment:
      JAVA_HOME: ${SNAP}/usr/lib/jvm/java-8-openjdk-amd64
